@echo off
mkdir ".github" 2>nul
echo # Copilot Instructions for projectdna-cli > ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ## Project Overview >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo **projectdna-cli** is a Python CLI tool built with Typer that analyzes and profiles software projects. It displays project metadata (tech stack, difficulty level, resume impact) in a structured format. >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ## Architecture >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ### Stack >> ".github\copilot-instructions.md"
echo - **Framework**: [Typer](https://typer.tiangolo.com/) - Modern Python CLI framework built on Click >> ".github\copilot-instructions.md"
echo - **Output**: [Rich](https://rich.readthedocs.io/) - Terminal formatting library for styled output >> ".github\copilot-instructions.md"
echo - **Entry Point**: `app.py` - Contains the Typer app instance and command definitions >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ### Command Structure >> ".github\copilot-instructions.md"
echo - Commands are defined as functions decorated with `@app.command\(\)` >> ".github\copilot-instructions.md"
echo - Current command: `analyze(project: str)` - Accepts a project name and displays analysis info >> ".github\copilot-instructions.md"
echo - Output uses Rich `Panel` for visual formatting >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ## Development Setup >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ### Dependencies >> ".github\copilot-instructions.md"
echo - **typer** - CLI framework >> ".github\copilot-instructions.md"
echo - **rich** - Terminal output formatting >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ### Installation >> ".github\copilot-instructions.md"
echo ``` >> ".github\copilot-instructions.md"
echo bash >> ".github\copilot-instructions.md"
echo pip install typer rich >> ".github\copilot-instructions.md"
echo ``` >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ### Running Commands >> ".github\copilot-instructions.md"
echo ``` >> ".github\copilot-instructions.md"
echo bash >> ".github\copilot-instructions.md"
echo # Run a specific command >> ".github\copilot-instructions.md"
echo python app.py analyze "my-project" >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo # View available commands >> ".github\copilot-instructions.md"
echo python app.py --help >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo # View help for a specific command >> ".github\copilot-instructions.md"
echo python app.py analyze --help >> ".github\copilot-instructions.md"
echo ``` >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ## Key Conventions >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo 1. **Command Definitions**: New commands should be added as functions decorated with `@app.command\(\)` in `app.py` >> ".github\copilot-instructions.md"
echo 2. **Output Format**: Use Rich's `Panel`, `print\(\)`, and other formatting options for styled terminal output >> ".github\copilot-instructions.md"
echo 3. **Parameter Typing**: Leverage Typer's support for type hints; use `str`, `int`, etc. to define CLI argument types >> ".github\copilot-instructions.md"
echo 4. **Help Text**: Add docstrings to command functions - Typer automatically converts them to CLI help text >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo ## Testing ^& Validation >> ".github\copilot-instructions.md"
echo. >> ".github\copilot-instructions.md"
echo Currently, no automated test suite exists. Manual testing: >> ".github\copilot-instructions.md"
echo ``` >> ".github\copilot-instructions.md"
echo bash >> ".github\copilot-instructions.md"
echo python app.py analyze "test-project" >> ".github\copilot-instructions.md"
echo ``` >> ".github\copilot-instructions.md"
